dictionaries:
  - name: Example Organization
    repo: user/repo
    webhook_secret: 0123456789abcdefghijklmnopqrstuv
    access_token: 0123456789abcdefghijklmnopqrstuv
slacks:
  - name: example
    dictionary: 0
    secret: 0123456789abcdefghijklmnopqrstuv
    access_token: 0123456789abcdefghijklmnopqrstuv
api_keys:
  - name: Example User
    token: 0123456789abcdefghijklmnopqrstuv
